apiVersion: v1
kind: Namespace
metadata:
  name: service-infra-whoami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-infra-whoami
  namespace: service-infra-whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-infra-whoami
  template:
    metadata:
      labels:
        app: service-infra-whoami
    spec:
      containers:
        - name: service-infra-whoami
          image: __AZURE_CR_URL__/v2/dify-poc/service-infra-whoami:latest
          resources:
            requests:
              cpu: '250m'
              memory: '128Mi'
            limits:
              cpu: '500m'
              memory: '256Mi'
          ports:
            - containerPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-service-infra-whoami
  namespace: service-infra-whoami
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-service-infra-whoami
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: service-cip-infra-whoami
  namespace: service-infra-whoami
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: service-infra-whoami
