trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

# Define Variables
variables:
  - group: arm-variables
  - name: POC_ENVIRONMENT
    value: poc

stages:
  - stage: buildAndPushDockerImage
    displayName: 'Build and Push Docker Image'
    trigger: manual
    jobs:
      - deployment: buildAndPushDockerImage
        displayName: 'Build and Push Docker Image'
        pool:
          vmImage: 'ubuntu-latest'
        environment: $(POC_ENVIRONMENT)
        strategy:
          runOnce:
            deploy:
              steps:
                # Must reclone repo.
                - checkout: self

                # Login to all services
                - task: AzureCLI@2
                  inputs:
                    #azureSubscription: 'AZRM_difyai-agent-builder-poc_Service_Connection'
                    azureSubscription: 'global-azdo-spn'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      set -e  # Fail if any command fails
                      echo ""
                      echo "Logging into Azure..."
                      az login --service-principal --username "$(AZURE_CLIENT_ID)" --password "$(AZURE_CLIENT_SECRET)" --tenant "$(AZURE_TENANT_ID)"
                      az account set --subscription "$(AZURE_SUBSCRIPTION_ID)"
                      az account show
                      echo ""
                      echo "Setting up Kubernetes credentials..."
                      az aks get-credentials --admin --name difyai-agent-builder-poc-cluster --resource-group difyai-agent-builder-poc
                      cat /home/vsts/.kube/config
                      echo ""
                      echo "Logging into Azure Container Registry..."
                      docker login https://crdifyaipoc001.azurecr.io -u $(az acr credential show -n crdifyaipoc001 | jq -r '.username') -p $(az acr credential show -n crdifyaipoc001 | jq -r '.passwords[0]|.value')
                      echo "List Files"
                      pwd
                      ls
                      echo ""
                      echo "Building docker image and pushing to registry..."
                      cd service-infra-whoami
                      docker build -t service-infra-whoami .
                      echo ""
                      echo "List docker images and build number..."
                      docker image ls
                      echo $(Build.BuildId)
                      echo ""
                      echo "Running docker image..."
                      docker run -d -p 8080:80 service-infra-whoami
                      echo ""
                      echo "Testing docker image..."
                      sleep 5
                      docker container ls
                      curl http://localhost:8080
                      curl -s  http://localhost:8080 -o /dev/null -w '%{http_code}' | grep 200
                      echo ""
                      echo "Stopping docker image..."
                      docker container ls
                      docker container rm $(docker container ls | grep service-infra-whoami | awk '{print $1}') --force
                      echo ""
                      echo "Tagging docker image..."
                      docker tag service-infra-whoami crdifyaipoc001.azurecr.io/v2/dify-poc/service-infra-whoami:1.1.$(Build.BuildId)
                      docker tag service-infra-whoami crdifyaipoc001.azurecr.io/v2/dify-poc/service-infra-whoami:latest
                      echo ""
                      echo "Pushing docker image..."
                      docker push --all-tags crdifyaipoc001.azurecr.io/v2/dify-poc/service-infra-whoami
                      echo ""
                      echo "Stage Successful"
                  displayName: 'Build and Push Docker Image'

  - stage: pullandDeploy
    displayName: 'Pull and Deploy Docker Image'
    trigger: manual
    jobs:
      - deployment: pullandDeploy
        displayName: 'Pull and Deploy Docker Image'
        pool:
          vmImage: 'ubuntu-latest'
        environment: $(POC_ENVIRONMENT)
        strategy:
          runOnce:
            deploy:
              steps:
                # Must reclone repo.
                - checkout: self

                # Login to all services
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'global-azdo-spn'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      set -e  # Fail if any command fails
                      echo ""
                      echo "Logging into Azure..."
                      az login --service-principal --username "$(AZURE_CLIENT_ID)" --password "$(AZURE_CLIENT_SECRET)" --tenant "$(AZURE_TENANT_ID)"
                      az account set --subscription "$(AZURE_SUBSCRIPTION_ID)"
                      az account show
                      echo ""
                      echo "Setting up Kubernetes credentials..."
                      az aks get-credentials --admin --name difyai-agent-builder-poc-cluster --resource-group difyai-agent-builder-poc
                      cat /home/vsts/.kube/config
                      echo ""
                      echo "Logging into Azure Container Registry..."
                      docker login https://crdifyaipoc001.azurecr.io -u $(az acr credential show -n crdifyaipoc001 | jq -r '.username') -p $(az acr credential show -n crdifyaipoc001 | jq -r '.passwords[0]|.value')
                      echo "List Files"
                      pwd
                      ls
                      cd service-infra-whoami
                      echo ""
                      echo "Get kubernetes namespaces..."
                      kubectl get ns
                      echo ""
                      echo "Deploy kubernetes pod..."
                      kubectl apply -f deployment.yaml
                      echo ""
                      echo "Get service ip..."
                      kubectl get service -n service-infra-whoami
                      echo ""
                      echo "Stage Successful"
                  displayName: 'Pull and Deploy Docker Image'
