# Define Variables
variables:
  - group: difyaiab-global-resource-infra-aks
  - name: LIFECYCLE_ENVIRONMENT
    value: '$(ADO_DEV_ENVIRONMENT)'

# Stage to Configure AKS Cluster
stages:
  - stage: configureAKSCluster
    # The stage displayName is not displayed in ADO but can be used for documentation purposes.
    displayName: 'Configure AKS Cluster'
    trigger: manual
    jobs:
      - deployment: configureAKSCluster
        # The deployment displayName is displayed in ADO under Jobs.
        displayName: 'Configure AKS Cluster'
        pool:
          vmImage: 'ubuntu-latest'
        # This is the environment in ADO where the results of this job will be displayed.
        environment: difyaiab-$(LIFECYCLE_ENVIRONMENT)-resource-infra-aks
        strategy:
          runOnce:
            deploy:
              steps:
                # Checkout GitHub Repository
                - checkout: self
                  # dispalyName: 'Checkout GitHub Repository'
                # Azure CLI Login Step.
                - task: AzureCLI@2
                  # The step display name will be displayed in ADO in the DOS window in light green.
                  displayName: 'Azure CLI Login'
                  inputs:
                    azureSubscription: '$(AZURE_SERVICE_SPN)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      set -e  # Fail if any command fails
                      echo "Logging into Azure..."
                      az login --service-principal --username "$(AZURE_CLIENT_ID)" --password "$(AZURE_CLIENT_SECRET)" --tenant "$(AZURE_TENANT_ID)"
                      az account set --subscription "$(AZURE_SUBSCRIPTION_ID)"
                      az account show
                      echo "Azure login successful"

                # Traefik Install Step
                - task: AzureCLI@2
                  displayName: 'Install Traefik'
                  inputs:
                    azureSubscription: '$(AZURE_SERVICE_SPN)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      set -e  # Fail if any command fails
                      echo ""
                      echo "Logging into Azure..."
                      az login --service-principal --username "$(AZURE_CLIENT_ID)" --password "$(AZURE_CLIENT_SECRET)" --tenant "$(AZURE_TENANT_ID)"
                      az account set --subscription "$(AZURE_SUBSCRIPTION_ID)"
                      az account show
                      echo ""
                      echo "Setting up Kubernetes credentials..."
                      az aks get-credentials --admin --name difyai-agent-builder-poc-cluster --resource-group difyai-agent-builder-poc
                      cat /home/vsts/.kube/config
                      echo ""
                      #echo "Logging into Azure Container Registry..."
                      #docker login https://crdifyaipoc001.azurecr.io -u $(az acr credential show -n crdifyaipoc001 | jq -r '.username') -p $(az acr credential show -n crdifyaipoc001 | jq -r '.passwords[0]|.value')
                      #echo "List Files"
                      #pwd
                      #ls
                      echo ""
                      echo "Installing Traefik..."
                      cd resource-infra-aks/kubernetes-manifests/traefik
                      kubectl apply -f traefik01-ns.yaml
                      kubectl apply -f traefik02-crd.yaml
                      kubectl apply -f traefik03-crd-rbac.yaml
                      # Add helm upgrade --namespace=traefik traefik traefik/traefik --values=traefik-chart-values.yaml
                      kubectl get deployments.apps -n traefik | grep traefik || helm repo add traefik https://traefik.github.io/charts
                      kubectl get deployments.apps -n traefik | grep traefik || helm repo update
                      kubectl get deployments.apps -n traefik | grep traefik || helm install --namespace=traefik traefik traefik/traefik --values=traefik-chart-values.yaml
                      traefik_ip=$(kubectl get service -n traefik | grep traefik | grep LoadBalancer | awk '{print $4}' | xargs)
                      az network dns record-set a list --resource-group difyai-agent-builder-poc --zone-name aidifypoc.com | grep ipv4Address
                      kubectl apply -f traefik06-dashboard-secret.yaml
                      kubectl apply -f traefik07-dashboard-middleware.yaml
                      kubectl apply -f traefik08-dashboard-rule.yaml
                      echo ""
                      echo "Stage Successful"
