# Define Variables
variables:
  - group: difyaiab-global-resource-infra-aks
  - name: LIFECYCLE_ENVIRONMENT
    value: '$(ADO_DEV_ENVIRONMENT)'

# Stage to Deploy Terraform Backend Storage
stages:
  - stage: terraformBackendStorageDeployment
    # The stage displayName is not displayed in ADO but can be used for documentation purposes.
    displayName: 'Terraform Backend Storage Deployment'
    trigger: manual
    jobs:
      - deployment: terraformBackendStorageDeployment
        # The deployment displayName is displayed in ADO under Jobs.
        displayName: 'Terraform Backend Storage Deployment'
        pool:
          vmImage: 'ubuntu-latest'
        # This is the environment in ADO where the results of this job will be displayed.
        environment: difyaiab-global-resource-infra-aks
        strategy:
          runOnce:
            deploy:
              steps:
                # Azure CLI Login Step.
                - task: AzureCLI@2
                  # The step display name will be displayed in ADO in the DOS window in light green.
                  displayName: 'Azure CLI Login'
                  inputs:
                    azureSubscription: '$(AZURE_SERVICE_SPN)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      set -e  # Fail if any command fails
                      echo "Logging into Azure..."
                      az login --service-principal --username "$(AZURE_CLIENT_ID)" --password "$(AZURE_CLIENT_SECRET)" --tenant "$(AZURE_TENANT_ID)"
                      az account set --subscription "$(AZURE_SUBSCRIPTION_ID)"
                      az account show
                      echo "Azure login successful"
                # Show Logged In User.
                - task: AzureCLI@2
                  # The step display name will be displayed in ADO in the DOS window in light green.
                  displayName: 'Storage Account Creation'
                  inputs:
                    azureSubscription: '$(AZURE_SERVICE_SPN)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    ### NEED TO ADD STANDARD TAGS TO ST###
                    ### NEED TO ADD CONTAINER REGISTRY###
                    ### NEED TO TIE CONTAINER REGIRSTRY TO AKS###
                    ### NEED TO ADD PLAN###
                    ### NEED TO ADD DEPLOY AND DESTROY###
                    ### NEED TO ADD INGRESS###
                    ### NEED TO ADD PROMETHEUS###
                    ### NEED TO ADD UPTIME-KUMA###
                    ### NEED TO ADD TRAEFIK-WHOAMI###
                    ### NEED TO ADD NGINX-HELLO###
                    ### NEED TO ADD BE####
                    ### NEED TO ADD BE###
                    ### NEED TO ADD FE###
                    inlineScript: |
                      set -e  # Fail if any command fails
                      AZURE_ST_NAME="sttf$(AZURE_PROJECT_NAME)$(AZURE_PROJECT_INSTANCE)"
                      echo "Creating Storage Account $AZURE_ST_NAME..."
                      echo ""
                      if $(az storage account list | jq -r '.[]|.name' | grep -q $AZURE_ST_NAME); then 
                        echo "    Storage Account \"$AZURE_ST_NAME\" already exists."
                      else
                        az storage account create --resource-group "$(AZURE_RG_NAME)" --name $AZURE_ST_NAME --sku Standard_LRS --encryption-services blob
                        az storage container create --name tfstate --account-name $AZURE_ST_NAME --auth-mode login
                        echo "    Storage Account \"$AZURE_ST_NAME\" and Container \"tfstate\" created."
                      fi
                      echo ""
                      echo "Storage Account creation complete"

  - stage: terraformCodeValidation
    # The stage displayName is not displayed in ADO but can be used for documentation purposes.
    displayName: 'Terraform Code Validation'
    trigger: manual
    jobs:
      - deployment: terraformCodeValidation
        # The deployment displayName is displayed in ADO under Jobs.
        displayName: 'Terraform Code Validation'
        pool:
          vmImage: 'ubuntu-latest'
        # This is the environment in ADO where the results of this job will be displayed.
        environment: 'difyaiab-$(LIFECYCLE_ENVIRONMENT)-resource-infra-aks'
        strategy:
          runOnce:
            deploy:
              steps:
                # Checkout GitHub Repository
                - checkout: self
                  # dispalyName: 'Checkout GitHub Repository'
                # Azure CLI Login (Required for Terraform authentication)
                - task: AzureCLI@2
                  displayName: 'Azure CLI Login'
                  inputs:
                    azureSubscription: '$(AZURE_SERVICE_SPN)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      set -e  # Fail if any command fails
                      echo "Logging into Azure..."
                      az login --service-principal --username "$(AZURE_CLIENT_ID)" --password "$(AZURE_CLIENT_SECRET)" --tenant "$(AZURE_TENANT_ID)"
                      az account set --subscription "$(AZURE_SUBSCRIPTION_ID)"
                      az account show
                      # Debug Commands
                      # pwd
                      # echo '$(System.DefaultWorkingDirectory)/$(REPO_TFMANIFEST_FOLDER)'
                      # ls
                      echo "Azure login successful"
                - task: TerraformInstaller@1
                  displayName: 'Terrafrom Installer'
                  inputs:
                    terraformVersion: 'latest'
                - task: TerraformTaskV4@4
                  displayName: 'Terrafrom Init'
                  inputs:
                    provider: 'azurerm'
                    command: 'init'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/$(REPO_TFMANIFEST_FOLDER)'
                    backendServiceArm: '$(AZURE_SERVICE_SPN)'
                    backendAzureRmResourceGroupName: '$(AZURE_RG_NAME)'
                    backendAzureRmStorageAccountName: 'sttf$(AZURE_PROJECT_NAME)$(AZURE_PROJECT_INSTANCE)'
                    backendAzureRmContainerName: 'tfstate'
                    backendAzureRmKey: 'aks-validate.tfstate'
                    allowTelemetryCollection: false
                - task: TerraformTaskV4@4
                  displayName: 'Terrafrom Validate'
                  inputs:
                    command: 'validate'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/$(REPO_TFMANIFEST_FOLDER)'
                    allowTelemetryCollection: false

  - stage: backendInfrastructureDestruction
    # The stage displayName is not displayed in ADO but can be used for documentation purposes.
    displayName: 'Backend Infrastructure Destruction'
    trigger: manual
    jobs:
      - deployment: backendInfrastructureDestruction
        # The deployment displayName is displayed in ADO under Jobs.
        displayName: 'Backend Infrastructure Destruction'
        pool:
          vmImage: 'ubuntu-latest'
        # This is the environment in ADO where the results of this job will be displayed.
        environment: difyaiab-global-resource-infra-aks
        strategy:
          runOnce:
            deploy:
              steps:
                # Azure CLI Login Step.
                - task: AzureCLI@2
                  # The step display name will be displayed in ADO in the DOS window in light green.
                  displayName: 'Azure CLI Login'
                  inputs:
                    azureSubscription: 'global-azdo-spn'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      set -e  # Fail if any command fails
                      echo "Logging into Azure..."
                      az login --service-principal --username "$(AZURE_CLIENT_ID)" --password "$(AZURE_CLIENT_SECRET)" --tenant "$(AZURE_TENANT_ID)"
                      az account set --subscription "$(AZURE_SUBSCRIPTION_ID)"
                      az account show
                      echo "Azure login successful"
                # Show Logged In User.
                - task: AzureCLI@2
                  # The step display name will be displayed in ADO in the DOS window in light green.
                  displayName: 'Storage Account Deletion'
                  inputs:
                    azureSubscription: 'global-azdo-spn'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      set -e  # Fail if any command fails
                      AZURE_ST_NAME="sttf$(AZURE_PROJECT_NAME)$(AZURE_PROJECT_INSTANCE)"
                      echo "Deleting Storage Account $AZURE_ST_NAME..."
                      echo ""
                      if $(az storage account list | jq -r '.[]|.name' | grep -q $AZURE_ST_NAME); then
                        az storage account delete --name $AZURE_ST_NAME -g "$(AZURE_RG_NAME)" --yes
                        echo "    Storage Account \"$AZURE_ST_NAME\" deleted."
                      else
                        echo "    Storage Account \"$AZURE_ST_NAME\" does not exist."
                      fi
                      echo ""
                      echo "Storage Account deletion complete"
