deployment:
  replicas: null

resources:
  requests:
    cpu: '100m'
    memory: '50Mi'
  limits:
    cpu: '300m'
    memory: '150Mi'

autoscaling:
  enabled: true
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

ingressRoute:
  dashboard:
    matchRule: Host(`localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    middlewares:
      - name: traefik-dashboard-basicauth
    enabled: true

logs:
  access:
    enabled:
      true
      #filePath: "/var/log/traefik/access.log"
