deployment:
  replicas: null

resources:
  requests:
    cpu: '100m'
    memory: '50Mi'
  limits:
    cpu: '300m'
    memory: '150Mi'

autoscaling:
  enabled: true
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

service:
  spec:
    externalTrafficPolicy: Local  # Preserve IP from LB to AKS

ports:
  web:
    forwardedHeaders:
      # -- Trust forwarded headers information (X-Forwarded-*).
      trustedIPs:
        - '127.0.0.1/32'
        - '192.168.1.1/24'
        - '10.0.0.0/8'
        - '172.16.0.0/12'
        - '128.85.200.44/32'
      insecure: false
    proxyProtocol:
      # -- Enable the Proxy Protocol header parsing for the entry point
      trustedIPs:
        - '127.0.0.1/32'
        - '192.168.1.1/24'
        - '10.0.0.0/8'
        - '172.16.0.0/12'
        - '128.85.200.44/32'
      insecure: false

ingressRoute:
  dashboard:
    matchRule: Host(`localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    middlewares:
      - name: traefik-dashboard-basicauth
    enabled: true

logs:
  access:
    enabled:
      true
      #filePath: "/var/log/traefik/access.log"
