/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './../../routes/__root'

// Create Virtual Routes

const AgentBuilderLazyImport = createFileRoute('/agent-builder')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AgentBuilderLazyRoute = AgentBuilderLazyImport.update({
  id: '/agent-builder',
  path: '/agent-builder',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./../../routes/agent-builder.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./../../routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/agent-builder': {
      id: '/agent-builder'
      path: '/agent-builder'
      fullPath: '/agent-builder'
      preLoaderRoute: typeof AgentBuilderLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/agent-builder': typeof AgentBuilderLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/agent-builder': typeof AgentBuilderLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/agent-builder': typeof AgentBuilderLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent-builder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent-builder'
  id: '__root__' | '/' | '/agent-builder'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AgentBuilderLazyRoute: typeof AgentBuilderLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AgentBuilderLazyRoute: AgentBuilderLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/agent-builder"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/agent-builder": {
      "filePath": "agent-builder.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
